name: HACS Validation
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: HACS Validation
        uses: "hacs/action@main"
        with:
          category: "integration"
